//@version=4

// Use same RSI calculation but change "price" to "volume"

study(title="Relative Strength Index - Volume", shorttitle="RSI-V", format=format.volume, precision=2, resolution="")
len = input(14, minval=1, title="Length")
is_bull_bar = change(close) >= 0 ? 1 : -1
up = rma(max(volume * is_bull_bar, 0), len)
down = rma(abs(min(volume * is_bull_bar, 0)), len)
rsi_v = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
plot(rsi_v, "RSI Volume", color=#8E1599)
band1 = hline(70, "Upper Band", color=#C0C0C0)
bandm = hline(50, "Middle Band", color=color.new(#C0C0C0, 50))
band0 = hline(30, "Lower Band", color=#C0C0C0)
